name: "Setup environment"
description: "setup"

runs:
  using: "composite"
  steps:
    - name: "Setup :: Node"
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: "npm"

    - name: "Bootstrap"
      shell: bash
      run: |
        npm ci

    - name: "Check :: lock"
      if: runner.os == 'Linux'
      shell: bash
      run: git diff --exit-code -- package-lock.json

    - name: "Check :: format"
      if: runner.os == 'Linux'
      shell: bash
      run: |
        npm run format:check

    - name: "Install :: Playwright Chromium"
      if: runner.os == 'Linux'
      shell: bash
      run: |
        npx playwright install --with-deps chromium
