name: "Setup environment"
description: "setup"

runs:
  using: "composite"
  steps:
    - name: "Setup :: Node"
      uses: actions/setup-node@v3
      with:
        node-version: 22
        cache: "yarn"

    - name: "Bootstrap"
      shell: bash
      run: |
        yarn install

    - name: "Check :: yarn.lock"
      shell: bash
      run: |
        git diff yarn.lock;
        [ "0" == "$(git diff yarn.lock | wc -l | tr -d ' ')" ]

    - name: "Check :: format"
      shell: bash
      run: |
        yarn format:check
