name: "Setup environment"
description: "setup"

runs:
  using: "composite"
  steps:
    - name: "Setup :: Node"
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: "npm"

    - name: "Bootstrap"
      shell: bash
      run: |
        npm install

    - name: "Check :: lock"
      shell: bash
      run: |
        git diff package-lock.json;
        [ "0" == "$(git diff package-lock.json | wc -l | tr -d ' ')" ]

    - name: "Check :: format"
      shell: bash
      run: |
        npm run format:check
