name: "Setup environment"
description: "setup"

runs:
  using: "composite"
  steps:
    - name: "Setup :: Node"
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: "npm"

    - name: "Bootstrap"
      shell: bash
      run: |
        npm ci

    - name: "Check :: lock"
      shell: bash
      run: git diff --exit-code -- package-lock.json

    - name: "Check :: format"
      shell: bash
      run: |
        npm run format:check
